/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_live'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/bootstrap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IdentityController_bootstrap'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IdentityController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IdentityController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/accept-link': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IdentityController_accept'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IdentityController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_sessions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/sessions/{id}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IdentityController_revoke'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/members/{id}/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_memberSessions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_members'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IdentityController_invite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/members/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['IdentityController_update'];
    trace?: never;
  };
  '/api/v1/identity/members/{id}/recovery': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['IdentityController_recovery'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_roles'];
    put?: never;
    post: operations['IdentityController_createRole'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_permissions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/roles/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['IdentityController_updateRole'];
    trace?: never;
  };
  '/api/v1/identity/team-candidates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_candidates'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/teams': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_teams'];
    put?: never;
    post: operations['IdentityController_createTeam'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/identity/teams/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['IdentityController_updateTeam'];
    trace?: never;
  };
  '/api/v1/identity/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['IdentityController_audit'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers/duplicates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommercialController_checkDuplicates'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommercialController_listCustomers'];
    put?: never;
    post: operations['CommercialController_createCustomer'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers/{customerId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommercialController_getCustomer'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['CommercialController_updateCustomer'];
    trace?: never;
  };
  '/api/v1/customers/{customerId}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_archiveCustomer'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers/{customerId}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_restoreCustomer'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers/{customerId}/contacts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_addContact'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers/{customerId}/contacts/{contactId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['CommercialController_deleteContact'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers/{customerId}/addresses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_addAddress'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/customers/{customerId}/utility-units': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommercialController_listUtilityUnits'];
    put?: never;
    post: operations['CommercialController_createUtilityUnit'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/utility-units/{utilityUnitId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['CommercialController_updateUtilityUnit'];
    trace?: never;
  };
  '/api/v1/opportunities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommercialController_listOpportunities'];
    put?: never;
    post: operations['CommercialController_createOpportunity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/opportunities/{opportunityId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommercialController_getOpportunity'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['CommercialController_updateOpportunity'];
    trace?: never;
  };
  '/api/v1/opportunities/{opportunityId}/qualify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_qualifyOpportunity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/opportunities/{opportunityId}/lose': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_loseOpportunity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/opportunities/{opportunityId}/reopen': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_reopenOpportunity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/activities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['CommercialController_listActivities'];
    put?: never;
    post: operations['CommercialController_createActivity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/activities/{activityId}/complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_completeActivity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/activities/{activityId}/reschedule': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_rescheduleActivity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/activities/{activityId}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CommercialController_cancelActivity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BootstrapDto: {
      email: string;
      password: string;
      name: string;
      organization: string;
    };
    CommandResultDto: {
      id: string;
    };
    LoginDto: {
      email: string;
      password: string;
    };
    GrantDto: {
      permission: string;
      /** @enum {string} */
      scope: 'own' | 'team' | 'organization' | 'assigned' | 'linked' | 'domain';
    };
    ContextDto: {
      id: string;
      name: string;
      email: string;
      roleId: string;
      roleName: string;
      status: string;
      version: number;
      userId: string;
      organizationId: string;
      organizationName: string;
      sessionId: string;
      grants: components['schemas']['GrantDto'][];
      teamIds: string[];
    };
    AcceptLinkDto: {
      token: string;
      password: string;
    };
    SessionViewDto: {
      id: string;
      device: string;
      current: boolean;
      createdAt: string;
      lastSeenAt: string;
    };
    MemberViewDto: {
      id: string;
      name: string;
      email: string;
      roleId: string;
      roleName: string;
      status: string;
      version: number;
    };
    InviteDto: {
      email: string;
      name: string;
      roleId: string;
    };
    LinkResultDto: {
      id: string;
      token: string;
      expiresAt: string;
    };
    UpdateMemberDto: {
      version: number;
      roleId: string;
      /** @enum {string} */
      status: 'active' | 'blocked';
    };
    RoleViewDto: {
      name: string;
      grants: components['schemas']['GrantDto'][];
      version?: number;
      id: string;
    };
    RoleDto: {
      name: string;
      grants: components['schemas']['GrantDto'][];
      version?: number;
    };
    CandidateDto: {
      id: string;
      name: string;
    };
    TeamViewDto: {
      name: string;
      memberIds: string[];
      version?: number;
      id: string;
    };
    TeamDto: {
      name: string;
      memberIds: string[];
      version?: number;
    };
    AuditViewDto: {
      id: string;
      action: string;
      actorId: string | null;
      entityId: string | null;
      createdAt: string;
      traceId: string;
    };
    DuplicateMatchDto: {
      /** @enum {string} */
      strength: 'STRONG' | 'MODERATE';
      reason: string;
      customerId: string;
      customerName: string;
      taxId?: string;
    };
    CustomerContactViewDto: {
      id: string;
      type: string;
      value: string;
      label?: string;
      isPrimary: boolean;
    };
    AddressViewDto: {
      id: string;
      postalCode: string;
      street: string;
      number: string;
      complement?: string;
      district?: string;
      city: string;
      state: string;
      isPrimary: boolean;
    };
    UtilityUnitViewDto: {
      id: string;
      organizationId: string;
      customerId: string;
      distributorName: string;
      externalCode?: string;
      consumerClass: string;
      tariffMode: string;
      connectionType: string;
      voltage: string;
      addressId?: string;
      version: number;
      createdAt: string;
      updatedAt: string;
    };
    CustomerOpportunitySummaryDto: {
      id: string;
      code: string;
      title: string;
      state: string;
    };
    CustomerViewDto: {
      id: string;
      organizationId: string;
      kind: string;
      legalName: string;
      tradeName?: string;
      taxId?: string;
      stateRegistration?: string;
      status: string;
      notes?: string;
      version: number;
      createdAt: string;
      updatedAt: string;
      contacts?: components['schemas']['CustomerContactViewDto'][];
      addresses?: components['schemas']['AddressViewDto'][];
      utilityUnits?: components['schemas']['UtilityUnitViewDto'][];
      opportunities?: components['schemas']['CustomerOpportunitySummaryDto'][];
    };
    CustomerListResponseDto: {
      items: components['schemas']['CustomerViewDto'][];
      total: number;
    };
    CreateCustomerDto: {
      /**
       * @default PERSON
       * @enum {string}
       */
      kind: 'PERSON' | 'COMPANY';
      legalName: string;
      tradeName?: string;
      taxId?: string;
      stateRegistration?: string;
      notes?: string;
      phone?: string;
      email?: string;
      postalCode?: string;
      street?: string;
      number?: string;
      complement?: string;
      district?: string;
      city?: string;
      state?: string;
      overrideDuplicate?: boolean;
    };
    UpdateCustomerDto: {
      expectedVersion: number;
      legalName?: string;
      tradeName?: string;
      taxId?: string;
      notes?: string;
    };
    ExpectedVersionDto: {
      expectedVersion: number;
    };
    AddContactDto: {
      /** @enum {string} */
      type: 'PHONE' | 'EMAIL' | 'WHATSAPP' | 'OTHER';
      value: string;
      label?: string;
      isPrimary?: boolean;
    };
    AddAddressDto: {
      postalCode: string;
      street: string;
      number: string;
      complement?: string;
      district?: string;
      city: string;
      state: string;
      isPrimary?: boolean;
    };
    CreateUtilityUnitDto: {
      distributorName: string;
      externalCode?: string;
      /** @default RESIDENTIAL */
      consumerClass: string;
      /** @default CONVENTIONAL */
      tariffMode: string;
      /** @default BIPHASIC */
      connectionType: string;
      /** @default 220V */
      voltage: string;
      addressId?: string;
    };
    UpdateUtilityUnitDto: {
      expectedVersion: number;
      distributorName?: string;
      externalCode?: string;
      consumerClass?: string;
      tariffMode?: string;
      connectionType?: string;
      voltage?: string;
    };
    OpportunityCustomerViewDto: {
      id: string;
      legalName: string;
      tradeName?: string;
      taxId?: string;
      contacts?: components['schemas']['CustomerContactViewDto'][];
    };
    OpportunityTransitionViewDto: {
      id: string;
      fromState: string;
      toState: string;
      reason: string;
      notes?: string;
      actorUserId?: string;
      createdAt: string;
    };
    OpportunityViewDto: {
      id: string;
      organizationId: string;
      code: string;
      customerId: string;
      utilityUnitId?: string;
      state: string;
      lossReason?: string;
      lossNotes?: string;
      title: string;
      source: string;
      projectType: string;
      needSummary: string;
      estimatedConsumption?: number;
      priority: string;
      expectedCloseDate?: string;
      ownerUserId: string;
      version: number;
      createdAt: string;
      updatedAt: string;
      customer?: components['schemas']['OpportunityCustomerViewDto'];
      transitions?: components['schemas']['OpportunityTransitionViewDto'][];
      utilityUnit?: components['schemas']['UtilityUnitViewDto'];
    };
    OpportunityListResponseDto: {
      items: components['schemas']['OpportunityViewDto'][];
      total: number;
    };
    FirstActivityDto: {
      /** @enum {string} */
      type: 'CALL' | 'MESSAGE' | 'MEETING' | 'VISIT' | 'EMAIL' | 'TASK';
      subject: string;
      description?: string;
      dueAt: string;
    };
    CreateOpportunityDto: {
      customerId: string;
      utilityUnitId?: string;
      title: string;
      /** @default INBOUND */
      source: string;
      /** @default ON_GRID */
      projectType: string;
      needSummary: string;
      estimatedConsumption?: number;
      /**
       * @default WARM
       * @enum {string}
       */
      priority: 'COLD' | 'WARM' | 'HOT';
      expectedCloseDate?: string;
      ownerUserId?: string;
      firstActivity: components['schemas']['FirstActivityDto'];
    };
    UpdateOpportunityDto: {
      expectedVersion: number;
      title?: string;
      needSummary?: string;
      estimatedConsumption?: number;
      /** @enum {string} */
      priority?: 'COLD' | 'WARM' | 'HOT';
      expectedCloseDate?: string;
      ownerUserId?: string;
      utilityUnitId?: string;
    };
    QualifyOpportunityDto: {
      expectedVersion: number;
      confirmedNeedSummary: string;
      estimatedConsumption?: number;
      nextActivity?: components['schemas']['FirstActivityDto'];
    };
    LoseOpportunityDto: {
      expectedVersion: number;
      lossReason: string;
      lossNotes?: string;
    };
    ReopenOpportunityDto: {
      expectedVersion: number;
      justification: string;
    };
    ActivityOpportunityViewDto: {
      id: string;
      code: string;
      title: string;
      state: string;
    };
    ActivityCustomerViewDto: {
      id: string;
      legalName: string;
    };
    ActivityAssigneeViewDto: {
      id: string;
      name: string;
      email: string;
    };
    ActivityViewDto: {
      id: string;
      organizationId: string;
      opportunityId?: string;
      customerId?: string;
      type: string;
      subject: string;
      description?: string;
      assigneeUserId: string;
      dueAt: string;
      status: string;
      resultCode?: string;
      resultNotes?: string;
      completedAt?: string;
      previousActivityId?: string;
      version: number;
      createdAt: string;
      updatedAt: string;
      opportunity?: components['schemas']['ActivityOpportunityViewDto'];
      customer?: components['schemas']['ActivityCustomerViewDto'];
      assignee?: components['schemas']['ActivityAssigneeViewDto'];
    };
    CreateActivityDto: {
      opportunityId?: string;
      customerId?: string;
      /** @enum {string} */
      type: 'CALL' | 'MESSAGE' | 'MEETING' | 'VISIT' | 'EMAIL' | 'TASK';
      subject: string;
      description?: string;
      assigneeUserId?: string;
      dueAt: string;
    };
    CompleteActivityDto: {
      expectedVersion: number;
      resultCode: string;
      resultNotes?: string;
      nextActivity?: components['schemas']['FirstActivityDto'];
    };
    RescheduleActivityDto: {
      expectedVersion: number;
      dueAt: string;
      notes?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  IdentityController_bootstrap: {
    parameters: {
      query?: never;
      header: {
        'x-bootstrap-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BootstrapDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContextDto'];
        };
      };
    };
  };
  IdentityController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContextDto'];
        };
      };
    };
  };
  IdentityController_accept: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AcceptLinkDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContextDto'];
        };
      };
    };
  };
  IdentityController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionViewDto'][];
        };
      };
    };
  };
  IdentityController_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_memberSessions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionViewDto'][];
        };
      };
    };
  };
  IdentityController_members: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MemberViewDto'][];
        };
      };
    };
  };
  IdentityController_invite: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID estável por comando; repetir com o mesmo conteúdo retorna o resultado. */
        'idempotency-key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LinkResultDto'];
        };
      };
    };
  };
  IdentityController_update: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID estável por comando; repetir com o mesmo conteúdo retorna o resultado. */
        'idempotency-key': string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMemberDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_recovery: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID estável por comando; repetir com o mesmo conteúdo retorna o resultado. */
        'idempotency-key': string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LinkResultDto'];
        };
      };
    };
  };
  IdentityController_roles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoleViewDto'][];
        };
      };
    };
  };
  IdentityController_createRole: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID estável por comando; repetir com o mesmo conteúdo retorna o resultado. */
        'idempotency-key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RoleDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_permissions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string[];
        };
      };
    };
  };
  IdentityController_updateRole: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID estável por comando; repetir com o mesmo conteúdo retorna o resultado. */
        'idempotency-key': string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RoleDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_candidates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateDto'][];
        };
      };
    };
  };
  IdentityController_teams: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TeamViewDto'][];
        };
      };
    };
  };
  IdentityController_createTeam: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID estável por comando; repetir com o mesmo conteúdo retorna o resultado. */
        'idempotency-key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TeamDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_updateTeam: {
    parameters: {
      query?: never;
      header: {
        /** @description UUID estável por comando; repetir com o mesmo conteúdo retorna o resultado. */
        'idempotency-key': string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TeamDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandResultDto'];
        };
      };
    };
  };
  IdentityController_audit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditViewDto'][];
        };
      };
    };
  };
  CommercialController_checkDuplicates: {
    parameters: {
      query?: {
        taxId?: string;
        email?: string;
        phone?: string;
        name?: string;
        externalCode?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DuplicateMatchDto'][];
        };
      };
    };
  };
  CommercialController_listCustomers: {
    parameters: {
      query?: {
        search?: string;
        status?: string;
        skip?: string;
        take?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerListResponseDto'];
        };
      };
    };
  };
  CommercialController_createCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCustomerDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerViewDto'];
        };
      };
    };
  };
  CommercialController_getCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerViewDto'];
        };
      };
    };
  };
  CommercialController_updateCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCustomerDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerViewDto'];
        };
      };
    };
  };
  CommercialController_archiveCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExpectedVersionDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerViewDto'];
        };
      };
    };
  };
  CommercialController_restoreCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExpectedVersionDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerViewDto'];
        };
      };
    };
  };
  CommercialController_addContact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddContactDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CustomerContactViewDto'];
        };
      };
    };
  };
  CommercialController_deleteContact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
        contactId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CommercialController_addAddress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddAddressDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddressViewDto'];
        };
      };
    };
  };
  CommercialController_listUtilityUnits: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UtilityUnitViewDto'][];
        };
      };
    };
  };
  CommercialController_createUtilityUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customerId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUtilityUnitDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UtilityUnitViewDto'];
        };
      };
    };
  };
  CommercialController_updateUtilityUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        utilityUnitId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUtilityUnitDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UtilityUnitViewDto'];
        };
      };
    };
  };
  CommercialController_listOpportunities: {
    parameters: {
      query?: {
        state?: string;
        ownerUserId?: string;
        customerId?: string;
        search?: string;
        skip?: string;
        take?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpportunityListResponseDto'];
        };
      };
    };
  };
  CommercialController_createOpportunity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateOpportunityDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpportunityViewDto'];
        };
      };
    };
  };
  CommercialController_getOpportunity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        opportunityId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpportunityViewDto'];
        };
      };
    };
  };
  CommercialController_updateOpportunity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        opportunityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateOpportunityDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpportunityViewDto'];
        };
      };
    };
  };
  CommercialController_qualifyOpportunity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        opportunityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QualifyOpportunityDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpportunityViewDto'];
        };
      };
    };
  };
  CommercialController_loseOpportunity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        opportunityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoseOpportunityDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpportunityViewDto'];
        };
      };
    };
  };
  CommercialController_reopenOpportunity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        opportunityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReopenOpportunityDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpportunityViewDto'];
        };
      };
    };
  };
  CommercialController_listActivities: {
    parameters: {
      query?: {
        status?: string;
        assigneeUserId?: string;
        opportunityId?: string;
        customerId?: string;
        dueFrom?: string;
        dueTo?: string;
        overdue?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityViewDto'][];
        };
      };
    };
  };
  CommercialController_createActivity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateActivityDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityViewDto'];
        };
      };
    };
  };
  CommercialController_completeActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        activityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompleteActivityDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityViewDto'];
        };
      };
    };
  };
  CommercialController_rescheduleActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        activityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RescheduleActivityDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityViewDto'];
        };
      };
    };
  };
  CommercialController_cancelActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        activityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExpectedVersionDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityViewDto'];
        };
      };
    };
  };
}
